name: Deploy to Vercel

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Type Check
        run: npm run type-check

      - name: Run Unit Tests
        run: npm run test -- --ci --coverage
        env:
          MONGODB: ${{ secrets.MONGODB }}

      - name: Build Project
        run: npm run build

      - name: Deploy to Vercel
        run: |
          npm install -g vercel
          vercel --token=${{ secrets.VERCEL_TOKEN }} --prod --confirm --yes
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
